### ISSUE TITLE
need ipv6 data

### ISSUE THREAD

**Issue by dongshengme** [a76yyyy/czipdata#1]
ths guys, you are Awlsome！ Waiting for your ipv6~

**Comment by a76yyyy** [comment]
Thank you for your support, now this project contains the relevant content of the IPv6 Database!
IPv6 Datebase obtained from https://ip.zxinc.org/, for non-commercial use only.

**Comment by dongshengme** [comment]
> hank you for your support, now this project c

thank you!!!
